#!/system/bin/sh
# Thanks to zepplinrox & all of the XDA community.

# CIQ Killa
rm /data/system/appusagestats/*
rm /data/system/dropbox/*
rm /data/system/usagestats/*
rm /data/tombstones/*

# No Checkin or Logging
if [ -e /data/data/com.google.android.gsf/databases/gservices.db ]; then
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 'false' where name = 'perform_market_checkin' and value = 'true'";
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 'false' where name = 'checkin_dropbox_upload:system_update' and value = 'true'"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'market_force_checkin' and value = -1"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'checkin_interval'"
	sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value = 0 where name = 'secure:bandwidth_checkin_stat_interval'"
fi;
chmod 0444 /data/system/appusagestats
chmod 0444 /data/system/dropbox
chmod 0444 /data/system/usagestats
chmod 0000 /data/system/userbehavior.db
chmod 0000 /data/system/userbehavior.db-shm
chmod 0000 /data/system/userbehavior.db-wal
chmod 0000 /data/system/userbehavior.xml

if [ ! -f "/system/etc/passwd" ]; then
  echo "root::0:0:root:/data/local:/system/bin/sh" > /system/etc/passwd
  chmod 0666 /system/etc/passwd
fi
if [ ! -f "/system/etc/group" ]; then
  echo "root::0:" > /system/etc/group
  chmod 0666 /system/etc/group
fi

# VM Tweaks
busybox sysctl -e -w vm.dirty_writeback_centisecs=2000;
busybox sysctl -e -w vm.dirty_expire_centisecs=1000;
busybox sysctl -e -w vm.swappiness=1;
busybox sysctl -e -w vm.page-cluster=3;
busybox sysctl -e -w vm.drop_caches=3;
busybox sysctl -e -w vm.oom_kill_allocating_task=1;
busybox sysctl -e -w vm.panic_on_oom=0;
busybox sysctl -e -w vm.dirty_background_ratio=70;
busybox sysctl -e -w vm.dirty_ratio=95;
busybox sysctl -e -w vm.min_free_kbytes=8192;
busybox sysctl -e -w vm.vfs_cache_pressure=10;
busybox sysctl -e -w vm.laptop_mode=5;
busybox sysctl -e -w vm.overcommit_memory=1;
busybox sysctl -e -w vm.min_free_order_shift=4;
busybox sysctl -e -w vm.block_dump=0;
busybox sysctl -e -w vm.oom_dump_tasks=1;

# Net Tweaks
busybox sysctl -e -w net.core.wmem_max=1048576;
busybox sysctl -e -w net.core.rmem_max=1048576;
busybox sysctl -e -w net.ipv4.tcp_tw_recycle=1;
busybox sysctl -e -w net.ipv4.tcp_rmem='6144 87380 1048576';
busybox sysctl -e -w net.ipv4.tcp_wmem='6144 87380 1048576';
busybox sysctl -e -w net.ipv4.route.flush=1;
busybox sysctl -e -w net.ipv4.udp_rmem_min=6144;
busybox sysctl -e -w net.ipv4.udp_wmem_min=6144;
busybox sysctl -e -w net.core.optmem_max=20480;
busybox sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1;
echo 262144 > /proc/sys/net/core/netdev_max_backlog;
echo 262144 > /proc/sys/net/core/somaxconn;
busybox sysctl -e -w net.core.rmem_default=65535;
busybox sysctl -e -w net.core.wmem_default=65535;
busybox sysctl -e -w net.core.rmem_max=262144;
busybox sysctl -e -w net.core.wmem_max=262144;
busybox sysctl -e -w net.ipv4.tcp_fin_timeout=15;
busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1200;
busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=360000;
echo 5 > /proc/sys/net/ipv4/tcp_reordering;
echo 0 > /proc/sys/net/ipv4/tcp_slow_start_after_idle;
busybox sysctl -e -w net.ipv4.tcp_syn_retries=3;
busybox sysctl -e -w net.ipv4.tcp_synack_retries=2;
busybox sysctl -e -w net.ipv4.tcp_timestamps=0;
busybox sysctl -e -w net.ipv4.tcp_tw_reuse=1;
busybox sysctl -e -w net.ipv4.tcp_window_scaling=0;
busybox sysctl -e -w net.ipv4.conf.all.accept_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.accept_redirects=0;
busybox sysctl -e -w net.ipv4.conf.all.secure_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.secure_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.accept_source_route=0;
busybox sysctl -e -w net.ipv4.conf.all.accept_source_route=0;
busybox sysctl -e -w net.ipv4.ip_forward=0;
busybox sysctl -e -w net.ipv4.conf.all.send_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.send_redirects=0;
busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1;
busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1;
busybox sysctl -e -w net.ipv4.icmp_echo_ignore_broadcasts=1;       # Don't reply to broadcasts (prevents joining a smurf attack)
busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5;
busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30;
busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1;
busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024;
busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1;
busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1;
busybox sysctl -e -w net.ipv4.tcp_congestion_control=cubic;
busybox sysctl -e -w net.ipv4.tcp_syncookies=1;
busybox sysctl -e -w net.ipv4.tcp_sack=1;
busybox sysctl -e -w net.ipv4.tcp_fack=1;
busybox sysctl -e -w net.ipv4.tcp_rfc1337=1;
busybox sysctl -e -w net.ipv4.ip_no_pmtu_disc=0;
busybox sysctl -e -w net.ipv4.tcp_ecn=0;
busybox sysctl -e -w net.unix.max_dgram_qlen=50;

# microSD Card
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
echo "2056" > /sys/block/mmcblk0/bdi/read_ahead_kb;
echo "2056" > /sys/block/mmcblk0/queue/read_ahead_kb;

# Memory Tweaks
busybox sysctl -e -w kernel.panic=1;
busybox sysctl -e -w kernel.random.read_wakeup_threshold=128;
busybox sysctl -e -w kernel.random.write_wakeup_threshold=256;
busybox sysctl -e -w kernel.panic_on_oops=1;
busybox sysctl -e -w kernel.sched_compat_yield=1;
busybox sysctl -e -w kernel.sched_child_runs_first=0;
busybox sysctl -e -w kernel.threads-max=524288;
busybox sysctl -e -w kernel.sched_latency_ns=18000000;
busybox sysctl -e -w kernel.sched_min_granularity_ns=1500000;
busybox sysctl -e -w kernel.sched_wakeup_granularity_ns=3000000;
busybox sysctl -e -w kernel.sched_shares_ratelimit=256000;
busybox sysctl -e -w kernel.sched_features=24189;
busybox sysctl -e -w kernel.hung_task_timeout_secs=30;
busybox sysctl -e -w kernel.msgmni=2048;
busybox sysctl -e -w kernel.msgmax=65536;
busybox sysctl -e -w kernel.shmmni=4096;
busybox sysctl -e -w kernel.shmall=2097152;
busybox sysctl -e -w kernel.shmmax=268435456;
busybox sysctl -e -w kernel.sem='500 512000 64 2048';

# Filesystem Tweaks
busybox mount -t debugfs none /sys/kernel/debug 2>/dev/null;
echo "NO_NORMALIZED_SLEEPER" > /sys/kernel/debug/sched_features;
echo "NO_NEW_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features;
busybox umount /sys/kernel/debug;
echo "noop" > /sys/block/mmcblk0/queue/scheduler;
echo "noop" > /sys/block/mmcblk1/queue/scheduler;
echo "2048" > /sys/block/mmcblk0/queue/read_ahead_kb;
echo "2048" > /sys/block/mmcblk1/queue/read_ahead_kb;
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
busybox sysctl -e -w fs.lease-break-time=10;
busybox sysctl -e -w fs.file-max=524288;
busybox sysctl -e -w fs.inotify.max_queued_events=32000;
busybox sysctl -e -w fs.inotify.max_user_instances=256;
busybox sysctl -e -w fs.inotify.max_user_watches=10240;

# Mounting Teaks
mount -o ro,remount,nodev,nodiratime,noatime,delalloc,noauto_da_alloc /system /system
mount -o remount,nodev,nodiratime,noatime,delalloc,noauto_da_alloc,barrier=0 /cache /cache
mount -o remount,nodev,nodiratime,noatime,delalloc,noauto_da_alloc /data /data
